### ISSUE TITLE
Consider A Build Script?

### ISSUE THREAD

**Issue by ateesdalejr** [Hum4n01d/timertron#1]
Would you consider sticking that one liner in a build script? So all you would have to do is:
 `person@device ~/timertron$ build`

**Comment by ateesdalejr** [comment]
Actually I'll start a PR with my changes.

**Comment by Hum4n01d** [comment]
Hello there! Let me take a look

**Comment by Hum4n01d** [comment]
Ok I merged it. Thanks!

**Comment by Hum4n01d** [comment]
@TheUltimatum I just moved the build script into an npm script. Now you can just run `npm build`

**Comment by Hum4n01d** [comment]
I also added support for your git shell by changing the double ampersand with a semicolon
